services:
  - type: web
    name: altDataTable
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn "app:app" --bind 0.0.0.0:$PORT --worker-class gevent --workers 2
    healthCheckPath: /test
    envVars:
      - key: FLASK_ENV
        value: productio