"""Initial migration

Revision ID: a8ef88403e6a
Revises: 
Create Date: 2023-04-06 08:59:06.485099

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8ef88403e6a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_name', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workflow_step',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('likes', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('tool_description', sa.String(length=1000), nullable=True),
    sa.Column('huggingface_url', sa.String(length=200), nullable=True),
    sa.Column('github_url', sa.String(length=200), nullable=True),
    sa.Column('chatgpt_prompt', sa.String(length=1000), nullable=True),
    sa.Column('research_description', sa.String(length=1000), nullable=True),
    sa.Column('research_url', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('workflow_step')
    op.drop_table('task')
    # ### end Alembic commands ###
